FROM ghcr.io/uoy-robostar/ros2-tb3:main

# Install pangolin dependencies
# RUN sudo apt update && sudo apt install -y curl zip unzip tar nasm

# RUN git clone https://github.com/Microsoft/vcpkg.git \
#     cd vcpkg \
#     ./bootstrap-vcpkg.sh -disableMetrics \
#     ./vcpkg integrate install \
#     ./vcpkg install pangolin \